name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: PhysPropertiesBOT docker images
      run: docker build ./python-bot/ --file ./python-bot/Dockerfile --tag physpropertiesbot-bot:$(date +%s) && docker build ./python-api/ --file ./python-api/Dockerfile --tag physpropertiesbot-api:$(date +%s)

